### ISSUE TITLE
Issues in Train your own YOLO, Run Inference

### ISSUE THREAD

**Issue by Ishan-10038** [bhadreshpsavani/CarPartsDetectionChallenge#16]
When I am running this code TrainyourOwn YOLO on jupyter notebook, I am facing some issues wrt part 2 and part 3 Train your own YOLO, Run Inference.

command 1)    !python Minimal_Example.py
Issue: 2021-04-27 10:12:08.182059: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-04-27 10:12:08.182366: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Ishan.Borkar\Desktop\CarPartsDetectionChallenge-master\3_Inference\Detector.py", line 172, in <module>
    yolo = YOLO(
  File "C:\Users\Ishan.Borkar\Desktop\CarPartsDetectionChallenge-master\2_Training\src\keras_yolo3\yolo.py", line 45, in __init__
    self.sess = K.get_session()
  File "C:\Users\Ishan.Borkar\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 174, in get_session
    default_session = tf.get_default_session()
AttributeError: module 'tensorflow' has no attribute 'get_default_session'

Command 2) !python Train_YOLO.py
Issue: 2021-04-27 10:15:00.422370: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
Traceback (most recent call last):
  File "convert.py", line 286, in <module>
    _main(parser.parse_args())
  File "convert.py", line 101, in _main
    input_layer = Input(shape=(None, None, 3))
  File "C:\Users\Ishan.Borkar\Anaconda3\lib\site-packages\keras\engine\input_layer.py", line 175, in Input
    input_layer = InputLayer(batch_input_shape=batch_shape,
  File "C:\Users\Ishan.Borkar\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Ishan.Borkar\Anaconda3\lib\site-packages\keras\engine\input_layer.py", line 39, in __init__
    name = prefix + '_' + str(K.get_uid(prefix))
  File "C:\Users\Ishan.Borkar\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 74, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
2021-04-27 10:15:02.904858: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-04-27 10:15:02.905242: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
Traceback (most recent call last):
  File "Train_YOLO.py", line 172, in <module>
    model = create_model(
  File "C:\Users\Ishan.Borkar\Desktop\CarPartsDetectionChallenge-master\Utils\Train_Utils.py", line 69, in create_model
    K.clear_session()  # get a new session
  File "C:\Users\Ishan.Borkar\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 95, in clear_session
    tf.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

command 3: !python Detector.py
Issue: 2021-04-27 10:15:05.559213: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-04-27 10:15:05.559488: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
Traceback (most recent call last):
  File "Detector.py", line 172, in <module>
    yolo = YOLO(
  File "C:\Users\Ishan.Borkar\Desktop\CarPartsDetectionChallenge-master\2_Training\src\keras_yolo3\yolo.py", line 45, in __init__
    self.sess = K.get_session()
  File "C:\Users\Ishan.Borkar\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 174, in get_session
    default_session = tf.get_default_session()
AttributeError: module 'tensorflow' has no attribute 'get_default_session'

To rectify this issues I have used the commands like 
import tensorflow as tf
tf.get_default_graph()
tf.compat.v1.Session()
tf.compat.v1.get_default_session()
tf.compat.v1.reset_default_graph()
But still the same issues are there.
Please assist.

**Comment by bhadreshpsavani** [comment]
Hi @IshanBorkar10038,
Thanks for letting me know!
I will check it and fix it as soon as possible. 
Most probably by today

**Comment by IshanBorkar10038** [comment]
Thanks Bhadresh. yes please

**Comment by bhadreshpsavani** [comment]
Hi @Ishan-10038,

If you are still exploring this I would like to tell you that the issue has been fixed. I have updated the model weights link in the data folder. Once you download model weight using [script](https://github.com/bhadreshpsavani/CarPartsDetectionChallenge/blob/master/Data/Model_Weights/Download_Weights.sh) Inference can be done.

**Comment by Ishan-10038** [comment]
Thank you
