### ISSUE TITLE
Yolo cannot load model due to h5py

### ISSUE THREAD

**Issue by meassinal** [bhadreshpsavani/CarPartsDetectionChallenge#40]
Hi @bhadreshpsavani ,

First of all, I'd like to thank you for this tutorial. 

However, I cannot run `python Minimal_Example.py` successfully. I have the following error:

```
WARNING:tensorflow:From /private/var/www/CarPartsDetectionChallenge/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "/private/var/www/CarPartsDetectionChallenge/2_Training/src/keras_yolo3/yolo.py", line 74, in generate
    self.yolo_model = load_model(model_path, compile=False)
  File "/private/var/www/CarPartsDetectionChallenge/env/lib/python3.6/site-packages/keras/models.py", line 237, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "/private/var/www/CarPartsDetectionChallenge/env/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/private/var/www/CarPartsDetectionChallenge/env/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

In your `requirements.txt`, `h5py==2.9.0` and `tensorflow==1.13.2` may not be compatible versions. And, I have no idea which version may fit them together. 

I hope you have an idea and I really appreciate for your reply. Thanks.

**Comment by meassinal** [comment]
It was solved after I downloaded directly and placed in data folder.
